application: lunar-calendar-email-reminder
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: lunarcalendarportal.application

libraries:
- name: webapp2
  version: latest
