application: lunar-date-reminder
version: 2
runtime: python27
api_version: 1
threadsafe: true

builtins:
- deferred: on

handlers:
- url: /assets
  static_dir: assets
- url: /update_schema
  script: migration_handler.app
  login: admin
  secure: always
- url: /.*
  script: lunarcalendarportal.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
